<?php
require_once("../DataBase/DbConfig.php");
class HistorialModel
{




    public function  readBienHistorial($id)
    {
        $db = new MyDB;
        $sql = "
 SELECT * 
FROM BIEN_HISTORIAL
INNER JOIN HISTORIAL
ON BIEN_HISTORIAL.ID_HISTORIAL = HISTORIAL.ID_HISTORIAL
INNER JOIN UBICACION
ON HISTORIAL.ID_UBICACION = UBICACION.ID_UBICACION
INNER JOIN ITEM_GASTO
ON HISTORIAL.ID_ITEM_GASTO = ITEM_GASTO.ID_ITEM_GASTO
INNER JOIN PROVEEDOR
ON HISTORIAL.ID_PROVEEDOR = PROVEEDOR.ID_PROVEEDOR
INNER JOIN ORIGEN
ON HISTORIAL.ID_ORIGEN = ORIGEN.ID_ORIGEN
INNER JOIN OBSERVACION
ON HISTORIAL.ID_OBSERVACION = OBSERVACION.ID_OBSERVACION
INNER JOIN COMUNA
ON UBICACION.ID_COMUNA = COMUNA.ID_COMUNA

where BIEN_HISTORIAL.ID_BIEN= $id

;

  
    ";

        $ret = $db->query($sql);
        return  $ret;
        $db->close();
    }




    
}
